pythonProject/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view, name='index'),
    path('view', views.persons_view, name='persons_view'),
    path('add', views.person_add_view, name='person_add'),
    path('load-cities/', views.load_cities, name='load_cities'),
    path('<int:pk>/', views.person_update_view, name='person_change'),
    path('login/',views.login_page),
    path('logout',views.logout_f)
]

pythonProject/project/app/models.py
from django.db import models


class Voivodeship(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=50)
    voivodeship = models.ForeignKey(Voivodeship, on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'cities'

class Person(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    birthdate = models.CharField(max_length=50,null=True,blank=True)
    voivodeship = models.ForeignKey(Voivodeship,on_delete=models.SET_NULL,null=True,blank=True)
    city = models.ForeignKey(City,on_delete=models.SET_NULL,null=True,blank=True)
    pesel = models.CharField(max_length=11,null=True,blank=True)

class Comment(models.Model):
    city = models.ForeignKey(City,on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return

pythonProject/project/app/forms.py
from django import forms

from .models import Person, City


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'voivodeship' in self.data:
            try:
                voivodeship_id = int(self.data.get('voivodeship'))
                self.fields['city'].queryset = City.objects.filter(voivodeship_id=voivodeship_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.voivodeship.city_set.order_by('name')

pythonProject/project/app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate,login,logout

from django.contrib import messages

from .forms import PersonForm
from .models import Person
from .models import City

def home_view(request):
    return render(request, "welcome.html")

def person_add_view(request):
    my_form = PersonForm()
    cities = City.objects.all
    if request.method=="POST":
        my_form = PersonForm(request.POST)
        if my_form.is_valid():
            Person.objects.create(**my_form.cleaned_data)
            return redirect('persons_view')
    context = {
        "form": my_form
    }
    return render (request, "person_add.html", context)

def persons_view(request):
    model = Person
    persons = Person.objects.all()
    context = {
        'object_list': persons,
    }
    return render(request, "app/person_list.html",context)

def person_update_view(request, pk):
    person = get_object_or_404(Person, pk=pk)
    form = PersonForm(instance=person)
    if request.method == 'POST':
        form = PersonForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            return redirect('persons_view')
    return render(request, 'person_add.html', {'form': form})


def load_cities(request):
    voivodeship_id = request.GET.get('voivodeship_id')
    cities = City.objects.filter(voivodeship_id=voivodeship_id).all()
    return render(request, 'city_dropdown_list.html', {'cities': cities})

def login_page(request):
     login_page = True
     if request.user.is_authenticated:
        return redirect('index')
     else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                messages.info(request, 'Username OR password is incorrect')
        context = {
            'login_page': login_page
        }
        return render(request, 'login.html', context)

def logout_f (request):
    logout(request)
    return render(request, "welcome.html")

pythonProject/project/app/templates/app/person_list.html
{% extends 'index.html' %}
{% block content %}
<head>
<title>Persons view</title>
</head>
<div class="cointainer mb-3 mt-4">
    <table class="table table-striped table-bordered" id="persontable">
        <thead>
        <tr>
            <th>Name</th>
            <th>Surname</th>
            <th>Birthdate</th>
            <th>Voivodeship</th>
            <th>City</th>
            <th>Pesel</th>
            {% if user.is_superuser %}
            <th></th>
            <th></th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for person in object_list %}
        <tr>
            <td>{{ person.name }}</td>
            <td>{{ person.surname }}</td>
            <td>{{ person.birthdate }}</td>
            <td>{{ person.voivodeship }}</td>
            <td>{{ person.city }}</td>
            <td>{{ person.pesel }}</td>
            {% if user.is_superuser %}
            <td><a href="{{person.id}}">Edit</a></td>
            <td><a href="../admin/app/person/{{person.id}}/delete" target="_blank">Delete</a></td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<button type="button" class="btn btn-primary" onClick="window.location.reload();">Refresh</button>
{% endblock %}

pythonProject/project/app/templates/city_dropdown_list.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

pythonProject/project/app/templates/index.html
{%load static %}

<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/bootstrap.css' %}"
    />

<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="fs-3 navbar-brand" href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}" width="50" height="40" alt="" class="d-inline-block"> E-Person</a>
  </div>
    <div class="fs-3 position-relative position-absolute top-25 start-50 translate-middle-x">
          <div class="navbar-nav">
        <a class="nav-link" href="../add">Add</a>
        <a class="nav-link" href="../view">View</a>
              {% if user.is_authenticated %}
        <a class="nav-link" href="logout">Logout</a>
              {% else %}
        <a class="nav-link" href="../login">Login</a>
              {% endif %}
              {% if user.is_superuser %}
        <a class="nav-link" href="../admin" target="_blank">Panel</a>
              {% endif %}
      </div>
    </div>
</nav>
<div class="wrapper position-fixed top-60 start-50 translate-middle-x mt-50" >
    <div class="cointainer mb-3 mt-4">
    {% if user.is_authenticated or login_page %}
    {% block content %}
    {% endblock %}
    {% else %}
    <p style="color:red">This view is only allowed for registered users</p>
    {% endif %}
    </div>
</div>
</body>

pythonProject/project/app/templates/login.html
{% extends 'index.html' %}
{% block content %}
<title>Login</title>
<form method="POST" action="">
	{% csrf_token %}
	<input type="text" name="username" placeholder="Username..." class="form-control">
	<div class="input-group mb-2">
		<input type="password" name="password" placeholder="Password..." class="form-control" >
	</div>
	<input class="btn btn-primary" type="submit" value="Login">
</form>
{% for message in messages %}
<p id="messages">{{message}}</p>
{% endfor %}
{% endblock %}

pythonProject/project/app/templates/person_add.html
{% extends 'index.html' %}
{% block content %}
<head>
<title>Add person</title>
    <script>
        let names = ['Adam','Karol','Krystian','Ewelina','Anna','Marek','Tadeusz','Aleksandra','Beata','Adrian','Jacek','Michał','Dagmara','Katarzyna','Wojciech','Dominik','Albert']
        let surnames = ['Adamowicz','Nowak','Maciejewicz','Żak','Tomczak','Dudek','Urbaniak','Pająk','Gajda','Mikołajczyk','Bednarczyk','Kozioł','Klimek']

        function getRnd(min, max) {
         min = Math.ceil(min);
         max = Math.floor(max);
         return Math.floor(Math.random() * (max - min + 1) + min);
        }

        function fill(){
            document.getElementById('id_name').value = names[getRnd(0,16)];
            document.getElementById('id_surname').value = surnames[getRnd(0,12)];
            day = getRnd(1,30).toString();
            if(day.length == 1)
                day = '0' + day;
            month = getRnd(1,12).toString();
            if(month.length == 1)
                month = '0' + month;
            year = getRnd(1950,2015).toString();
            document.getElementById('id_birthdate').value = day+'.'+month+'.'+year;
            document.getElementById('id_pesel').value = year.substring(2,4)+month+day+getRnd(10000,99999);
        }
    </script>
</head>
<div class="cointainer mb-3 mt-4">
<form method='POST' id="personForm" data-cities-url="{% url 'load_cities' %}">{% csrf_token %}
    <div class="col-sm-5">
    {{ form.as_p}}
    </div>
    <br>
    <input type='submit' class="btn btn-primary" value="Save"/>
    <button type="button" class="btn btn-primary" href="#" onClick="fill()">Random</button>
    <input type='reset' class="btn btn-primary" value="Clear"/>
</form>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_voivodeship").change(function () {
        const url = $("#personForm").attr("data-cities-url");
        const voivodeshipId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'voivodeship_id': voivodeshipId
            },
            success: function (data) {
                $("#id_city").html(data);
                }
        });
    });
</script>
{% endblock %}

pythonProject/project/app/templates/welcome.html
{% extends 'index.html' %}
{% block content %}
<head>
<title>Welcome</title>
</head>
<div class="cointainer mb-3 mt-4">
    <p class="h4"><em>Welcome to the site </em><b>{{ user.username }}</b></p>
</div>
{% endblock %}